name: Releasing Development Version

on:
  push:
    branches:
    - pypi-setup

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r requirements-test.txt
    - name: Test with pytest
      run: pytest -v .

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Fetch tags
      run: git fetch --tags
    - name: Describe
      run: git describe --dirty --always
    - name: Install dependencies
      run: pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
      run: |
        python setup.py clean sdist bdist_wheel
        twine upload --skip-existing dist/*
